python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
python3 -m nbconvert --to python --execute NeuroSonic_1DCNN.ipynb
